#!/usr/bin/env node
var redis = require('redis');
var munin = require('../');
var filename = __filename.replace(__dirname+'/', '').replace('.js','');
//var jsonfile = __dirname + '/munin-redis.json';
var main = function(config){
    var rcl = redis.createClient(config['port'],config['host']);
    rcl.hset("nodejs-memoryusage-rss", "localhost", process.memoryUsage().rss);
    rcl.hset("nodejs-memoryusage-heaptotal", "localhost", process.memoryUsage().heapTotal);
    rcl.hset("nodejs-memoryusage-heapused", "localhost", process.memoryUsage().heapUsed);
    rcl.hset("nodejs-uptime", "localhost", process.uptime());
    rcl.quit(function(err){
    });
}
main({ host:'localhost', port:'6379' });
